services:
  - type: web
    name: deepnetsoft-backend
    runtime: node
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000